/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CalculatorsRouteImport } from './routes/calculators'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as MutualFundsRouteImport } from './routes/mutual-funds'
import { Route as PersonalFinanceRouteImport } from './routes/personal-finance'
import { Route as RealEstateRouteImport } from './routes/real-estate'
import { Route as ResourcesRouteImport } from './routes/resources'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsRoute = CalculatorsRouteImport.update({
  id: '/calculators',
  path: '/calculators',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const MutualFundsRoute = MutualFundsRouteImport.update({
  id: '/mutual-funds',
  path: '/mutual-funds',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalFinanceRoute = PersonalFinanceRouteImport.update({
  id: '/personal-finance',
  path: '/personal-finance',
  getParentRoute: () => rootRouteImport,
} as any)
const RealEstateRoute = RealEstateRouteImport.update({
  id: '/real-estate',
  path: '/real-estate',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculators': typeof CalculatorsRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/learn': typeof LearnRoute
  '/mutual-funds': typeof MutualFundsRoute
  '/personal-finance': typeof PersonalFinanceRoute
  '/real-estate': typeof RealEstateRoute
  '/resources': typeof ResourcesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculators': typeof CalculatorsRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/learn': typeof LearnRoute
  '/mutual-funds': typeof MutualFundsRoute
  '/personal-finance': typeof PersonalFinanceRoute
  '/real-estate': typeof RealEstateRoute
  '/resources': typeof ResourcesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calculators': typeof CalculatorsRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/learn': typeof LearnRoute
  '/mutual-funds': typeof MutualFundsRoute
  '/personal-finance': typeof PersonalFinanceRoute
  '/real-estate': typeof RealEstateRoute
  '/resources': typeof ResourcesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/calculators'
    | '/contact'
    | '/disclaimer'
    | '/learn'
    | '/mutual-funds'
    | '/personal-finance'
    | '/real-estate'
    | '/resources'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/calculators'
    | '/contact'
    | '/disclaimer'
    | '/learn'
    | '/mutual-funds'
    | '/personal-finance'
    | '/real-estate'
    | '/resources'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/calculators'
    | '/contact'
    | '/disclaimer'
    | '/learn'
    | '/mutual-funds'
    | '/personal-finance'
    | '/real-estate'
    | '/resources'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CalculatorsRoute: typeof CalculatorsRoute
  ContactRoute: typeof ContactRoute
  DisclaimerRoute: typeof DisclaimerRoute
  LearnRoute: typeof LearnRoute
  MutualFundsRoute: typeof MutualFundsRoute
  PersonalFinanceRoute: typeof PersonalFinanceRoute
  RealEstateRoute: typeof RealEstateRoute
  ResourcesRoute: typeof ResourcesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators': {
      id: '/calculators'
      path: '/calculators'
      fullPath: '/calculators'
      preLoaderRoute: typeof CalculatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mutual-funds': {
      id: '/mutual-funds'
      path: '/mutual-funds'
      fullPath: '/mutual-funds'
      preLoaderRoute: typeof MutualFundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal-finance': {
      id: '/personal-finance'
      path: '/personal-finance'
      fullPath: '/personal-finance'
      preLoaderRoute: typeof PersonalFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/real-estate': {
      id: '/real-estate'
      path: '/real-estate'
      fullPath: '/real-estate'
      preLoaderRoute: typeof RealEstateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CalculatorsRoute: CalculatorsRoute,
  ContactRoute: ContactRoute,
  DisclaimerRoute: DisclaimerRoute,
  LearnRoute: LearnRoute,
  MutualFundsRoute: MutualFundsRoute,
  PersonalFinanceRoute: PersonalFinanceRoute,
  RealEstateRoute: RealEstateRoute,
  ResourcesRoute: ResourcesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
